## YAML Template.
---
spring.cloud.config.uri: http://localhost:8888

management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"

---
spring.config.activate.on-profile: docker
spring.cloud.config.uri: http://config:8888