## YAML Template.
---
server.port: 9000
  
spring:
  config.import: "optional:configserver:"
  cloud.config.uri: http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost/oauth-server
    port: '3306'
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        #enable_lazy_load_no_trans: 'true'
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: 'true'

---
spring:
  config:
    activate.on-profile: docker
  datasource.url: jdbc:mysql://auth-db/oauth-server
  
server.port: 8080
