## YAML Template.
---
spring:
  cloud.gateway:
      routes:
        - id: service_a_get_all
          uri: lb://service-a
          predicates:
            - Path=/api/service-a/a1
            - Method=GET
          filters:
            - RewritePath=/api/service-a/a1, /a1
        - id: service_a_post_save
          uri: lb://service-a
          predicates:
            - Path=/api/service-a/a1
            - Method=POST
          filters:
            - RewritePath=/api/service-a/a1, /a1
        - id: service-a-swagger-ui-1
          uri: lb://service-a
          predicates:
            - Path=/openapi/service-a/**
          filters:
            - RewritePath=/openapi/service-a/(?<path>.*), /$\{path}
        - id: service-a-swagger-ui-2
          uri: lb://service-a
          predicates:
            - Path=/v3/api-docs/**

server:
  port: 8080
  forward-headers-strategy: framework
  
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

---
spring:
  config:
    activate.on-profile: docker

server.port: 8080
    