## YAML Template.
---
spring:
  application.name: Config
  profiles.active: native
  cloud.config.server.native.searchLocations: file:./src/main/resources/config-repo/
  
server.port: 8888

management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"

logging:
  level:
    root: trace
---
spring.config.activate.on-profile: docker
spring.cloud.config.server.native.searchLocations: file:/config-repo