## YAML Template.
---
spring:
  application.name: config
  profiles.active: native
  cloud.config.server.native.searchLocations: file:./src/main/resources/config-repo
  
server.port: 8888

management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
---
spring:
  config.activate.on-profile: docker
  cloud.config.server.native.searchLocations: file:/app/config-repo

server.port: 8080